/**
 * Generate Prover.toml for the Solva solvency circuit (v2 — full tree reconstruction).
 *
 * The new circuit verifies ALL leaves and reconstructs the tree in-circuit.
 * Format must match the circuit's main() signature:
 *
 *   fn main(
 *       root: pub Field,                   // public
 *       total_liabilities: pub Field,       // public
 *       num_addresses: pub Field,           // public
 *       addr_hashes: [Field; NUM_LEAVES],   // private
 *       balances: [Field; NUM_LEAVES],      // private
 *   )
 *
 * All field values are serialised as 0x-prefixed hex strings.
 */

import type { MerkleTree } from './buildTree.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const NUM_LEAVES = 16;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a bigint to a 0x-prefixed, zero-padded 64-character hex string.
 */
export function toHexField(value: bigint): string {
  const hex = value.toString(16).padStart(64, '0');
  return `0x${hex}`;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface LeafData {
  addrHash: bigint;
  balance: bigint;
}

// ---------------------------------------------------------------------------
// TOML generation
// ---------------------------------------------------------------------------

/**
 * Build the Prover.toml for the full-tree-reconstruction circuit.
 *
 * @param tree            - The complete Merkle tree (root used as public input)
 * @param leafData        - Per-leaf address hash + balance (up to NUM_LEAVES)
 * @param totalLiabilities - Total liabilities in satoshis
 * @returns A valid TOML string ready to be written to Prover.toml
 */
export function generateProverToml(
  tree: MerkleTree,
  leafData: LeafData[],
  totalLiabilities: bigint,
): string {
  const numAddresses = leafData.length;

  // Pad to NUM_LEAVES with zeros
  const addrHashes: bigint[] = new Array(NUM_LEAVES).fill(0n);
  const balances: bigint[] = new Array(NUM_LEAVES).fill(0n);

  for (let i = 0; i < Math.min(leafData.length, NUM_LEAVES); i++) {
    addrHashes[i] = leafData[i].addrHash;
    balances[i] = leafData[i].balance;
  }

  const addrArray = addrHashes.map((h) => `"${toHexField(h)}"`).join(', ');
  const balArray = balances.map((b) => `"${toHexField(b)}"`).join(', ');

  const lines: string[] = [
    '# ==========================================================================',
    '# Prover.toml — auto-generated by solva-tree-builder (v2)',
    '# Full tree reconstruction circuit: verifies ALL leaves + aggregate balance',
    '# ==========================================================================',
    '',
    '# Public inputs',
    `root = "${toHexField(tree.root)}"`,
    `total_liabilities = "${toHexField(totalLiabilities)}"`,
    `num_addresses = "${toHexField(BigInt(numAddresses))}"`,
    '',
    '# Private inputs — per-address data (padded to 16 with zeros)',
    `addr_hashes = [${addrArray}]`,
    `balances = [${balArray}]`,
    '',
  ];

  return lines.join('\n');
}
