/**
 * Generate Prover.toml for the Noir solvency circuit.
 * Format must match the circuit's main() signature exactly:
 *
 *   fn main(
 *       root: pub Field,              // public
 *       total_liabilities: pub Field,  // public
 *       leaf: Field,                   // private
 *       index: Field,                  // private
 *       hash_path: [Field; 4],         // private
 *       total_reserves: Field,         // private
 *   )
 *
 * All field values are serialised as 0x-prefixed hex strings, which is
 * the canonical format understood by Nargo's TOML parser.
 */

import type { MerkleTree, MerkleProof } from './buildTree.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a bigint to a 0x-prefixed, zero-padded 64-character hex string.
 * This is the standard encoding for BN254 field elements in Noir TOML files.
 */
export function toHexField(value: bigint): string {
  const hex = value.toString(16).padStart(64, '0');
  return `0x${hex}`;
}

// ---------------------------------------------------------------------------
// TOML generation
// ---------------------------------------------------------------------------

/**
 * Build the Prover.toml content string for the Solva solvency circuit.
 *
 * @param tree            - The complete Merkle tree (only root is used)
 * @param proof           - A Merkle proof for a specific leaf
 * @param totalReserves   - Sum of all UTXO values in satoshis
 * @param totalLiabilities - Total liabilities in satoshis
 * @returns A valid TOML string ready to be written to Prover.toml
 */
export function generateProverToml(
  tree: MerkleTree,
  proof: MerkleProof,
  totalReserves: bigint,
  totalLiabilities: bigint,
): string {
  const hashPathArray = proof.hashPath
    .map((h) => `"${toHexField(h)}"`)
    .join(', ');

  const lines: string[] = [
    '# ==========================================================================',
    '# Prover.toml -- auto-generated by solva-tree-builder',
    '# ==========================================================================',
    '',
    '# Public inputs',
    `root = "${toHexField(tree.root)}"`,
    `total_liabilities = "${toHexField(totalLiabilities)}"`,
    '',
    '# Private inputs',
    `leaf = "${toHexField(proof.leaf)}"`,
    `index = "${toHexField(BigInt(proof.index))}"`,
    `hash_path = [${hashPathArray}]`,
    `total_reserves = "${toHexField(totalReserves)}"`,
    '',
  ];

  return lines.join('\n');
}
