[sncast.sepolia]
account = "solva-deployer"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://api.cartridge.gg/x/starknet/sepolia"

[sncast.devnet]
account = "devnet-deployer"
url = "http://localhost:5050"
