[package]
name = "solvency_registry"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.5"
solvency_verifier = { path = "../solvency_verifier" }

[lib]

[[target.starknet-contract]]
