[package]
name = "lending_protocol"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.5"
solvency_registry = { path = "../solvency_registry" }
solvency_verifier = { path = "../solvency_verifier" }

[[target.starknet-contract]]
